driver:
  name: vagrant
  provider: virtualbox

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
  # chef_omnibus_install_options: -P chefdk
  # chef_omnibus_root: c:/opscode/chefdk

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver_config:
      box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      # The test cookbook is located in test/fixtures.
      # It is what puts secret keys, certs, etc. in place
      - recipe[test::default]
      - recipe[bjc_workstation::default]
    attributes:
      demo:
        domain_prefix: ''
        domain: 'automate-demo.com'
        enterprise: 'automate-demo'
        org: 'automate'
        hosts:
        workstations: 1
        workstation-number: 1
        versions:
          chefdk: 'stable-1.3.43'
    verifier:
      inspec_tests:
        - test/integration/default/controls