---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV["EC2_SSH_KEY_NAME"] %>
  region: us-west-2
  availability_zone: us-west-2c
  security_group_ids: sg-401e0e25
  iam_profile_name: testKitchenAndKnifeEc2
  subnet_id: subnet-5b32ef02
  instance_type: m3.large
  associate_public_ip: true
  tags:
    Name: "bjc_workstation-localdev-kitchen-instance"
    created-by: "test-kitchen"
    user: <%= ENV['USER'] %>
    X-Dept: Sales
    X-Contact: <%= ENV['USER'] %>
    X-Production: "false"

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver_config:
      image_id: ami-4428fa24
      retryable_tries: 80
    transport:
      ssh_key: <%= ENV["EC2_SSH_KEY_PATH"] %> # change it; this is needed so kitchen can retrieve the Admin password

suites:
  - name: default
    run_list:
      # The test cookbook is located in test/fixtures.
      # It is what puts secret keys, certs, etc. in place
      - recipe[test::default]
      - recipe[bjc_workstation::default]
    attributes:
      demo:
        domain_prefix: ''
        domain: 'automate-demo.com'
        enterprise: 'automate-demo'
        org: 'automate'
        hosts:
        workstations: 1
        workstation-number: 1
        versions:
          chefdk: 'stable-0.16.28'
