---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[test::default]
      - recipe[wombat::etc-hosts]
      - recipe[test::fixhosts]
      - recipe[bjc_automate::default]
    attributes:
      demo:
        domain_prefix: ''
        domain: 'automate-demo.com'
        enterprise: 'automate-demo'
        org: 'automate'
        build-nodes: 3
        hosts:
          chef: 172.31.54.10
          automate: 172.31.54.11
          compliance: 172.31.54.12
        versions:
          automate: 'stable-1.5.46'
          chefdk: 'stable-latest'
