---
driver:
  name: ec2
  require_chef_omnibus: true
  region: us-west-2
  security_group_ids: sg-2560a741
  availability_zone: us-west-2a
  instance_type: c3.large
  aws_ssh_key_id: <%= ENV["EC2_SSH_KEY_NAME"] %>
  tags:
    Name: "bjc-delivery-localdev-kitchen-instance"
    created-by: "bjc-delivery-test-kitchen"
    user: <%= ENV['USER'] %>

transport:
  username: ubuntu
  ssh_key: ~/.ssh/<%= ENV["EC2_SSH_KEY_PATH"] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[test::default]
      - recipe[bjc-delivery::default]
    attributes:
      demo:
        domain_prefix: ''
        domain: 'automate-demo.com'
        enterprise: 'automate-demo'
        org: 'automate'
        hosts:
          chef-server: '172.31.54.10'
          delivery: '172.31.54.11'
          compliance: '172.31.54.12'
        versions:
          delivery: 'stable-0.5.93'
          chefdk: 'stable-0.16.28'
